apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ko2tlzzbl-java-springboot
  janus-idp.io/tekton: ko2tlzzbl-java-springboot
  backstage.io/kubernetes-id: ko2tlzzbl-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ko2tlzzbl-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
